
pipeline:
  build:
    image: node:10-alpine
    commands:
      - yarn
      - yarn run export --basepath blog/
      - rm -rf /output/*
      - cp -r export/blog/* /output
    volumes:
      - /opt/docker/static/blog:/output